---
apiVersion: v1
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - name: "voteport"
      targetPort: 80
      port: 5000
      nodePort: 31000
  selector:
      app: vote
---

