apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - name: "result-svc"
      port: 5001
      targetPort: 80
      nodePort: 31001    
