FROM openjdk:8-jdk-alpine

LABEL maintainer="zein_tiz@yahoo.com"

ENV NEXUS_VERSION=latest
ENV NEXUS_HOME=/opt/nexus
ENV NEXUS_DATA=/nexus-data

RUN apk --no-cache add wget && \
    addgroup -S -g 1000 nexus && \
    adduser -S -G nexus -u 1000 nexus && \
    mkdir -p "$NEXUS_HOME" && \
    wget -O nexus.tar.gz "https://download.sonatype.com/nexus/3/latest-unix.tar.gz" && \
    tar -xzf nexus.tar.gz -C "$NEXUS_HOME" --strip-components=1 && \
    rm nexus.tar.gz* && \
    mkdir -p "$NEXUS_DATA" && \
    chown -R nexus:nexus "$NEXUS_HOME" "$NEXUS_DATA"

VOLUME "$NEXUS_DATA"

USER nexus

WORKDIR "$NEXUS_HOME"

EXPOSE 8081

CMD ["./bin/nexus", "run"]