###You need to specify one of the following as an environment variable:
#     - MYSQL_ROOT_PASSWORD
#     - MYSQL_ALLOW_EMPTY_PASSWORD
#     - MYSQL_RANDOM_ROOT_PASSWORD
#this stack works for me with swarm 
#or withput replicas we can scale up with docker service scale  wpstack_wordpress=3
# this code is work for me
version: "3.8"
services:
  db:
    image: mariadb:latest
    container_name: mysqllatestwp
    environment:
        MYSQL_DATABASE: zizidb
        MYSQL_USER: zizi
        MYSQL_PASSWORD: zizi
        MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: always
    volumes:
        - db:/var/lib/mysql
    networks:
        - wp-net


  wordpress:
    image: wordpress:latest
    container_name: wplatest
    environment:
       WORDPRESS_DB_HOST: db
       WORDPRESS_DB_USER: zizi
       WORDPRESS_DB_PASSWORD: zizi
       WORDPRESS_DB_NAME: zizidb
    volumes:
       - wordpress:/var/www/html
    deploy:
       replicas: 3
    ports:
      - 8080:80
    networks:
      - wp-net

networks:
  wp-net:
     name: wpnet
     driver: overlay
volumes:
  db:
  wordpress:
