apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-09-03T18:30:13Z"
  generateName: db-
  labels:
    app: db
    controller-revision-hash: db-d4d465b4c
    statefulset.kubernetes.io/pod-name: db-0
  name: db-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: db
    uid: bdb0e79e-1e8c-4036-ba8b-c0146002ad67
  resourceVersion: "469373"
  uid: 0d9ace38-1d15-4554-86b7-f2538f983123
spec:
  containers:
  - env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    image: postgres:15-alpine
    imagePullPolicy: Always
    name: db
    ports:
    - containerPort: 5432
      name: postgres
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: db-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-jrnxx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: db-0
  nodeName: zizi51
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: db
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: db-data
  - name: kube-api-access-jrnxx
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-09-03T18:30:13Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-09-03T18:40:09Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-09-03T18:40:09Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-09-03T18:30:13Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://edae3cf307566d6625789dff2348df3fce95150a6f29c066aeccf6f688717aa1
    image: docker.io/library/postgres:15-alpine
    imageID: docker.io/library/postgres@sha256:8bc3c893342c766481df5fde58fab6f1a1115b94eb56778126163305243e9709
    lastState: {}
    name: db
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-09-03T18:40:09Z"
  hostIP: 192.168.44.151
  phase: Running
  podIP: 10.244.4.4
  podIPs:
  - ip: 10.244.4.4
  qosClass: BestEffort
  startTime: "2023-09-03T18:30:13Z"
