## here is my play book code

- name: prepareation
  hosts: zizi51
  become: true


#### change my system dns to desire dns to increase download speed
  tasks:
       - name: replace dns lines all
         shell: echo "nameserver 10.202.10.202" > /etc/resolv.conf
       - name: change dns
         lineinfile:
             path: /etc/resolv.conf
             line: 'nameserver 10.202.10.102'
             state: present
       - name: reset adapter
         shell: netplan apply


#### swapp all off in all machines
       - name: uncomment line with swap word
         replace:
            path: /etc/fstab
            regexp: '^/swap'
            backup: yes
            replace: '#/swap'
       - name: verify swapoff
         shell: 'swapon -s'
         register: swap_out
       - debug: msg={{ swap_out }}
#### update catch and install cert for install containerd.io
       - name: install cert with update catch
         apt:
           name:
              - ca-certificates
              - curl
              - gnupg
           state: latest
           update_cache: yes
           force: yes
#### install keyring with permision to add docker repo to install containerd.io
       - name: install keyring
         file:
           path: /etc/apt/keyrings
           mode: 0755
           state: directory
       - name: gpg add
         shell: 'get_url -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg'
       - name: read permission for everyone for docker keyring gpg
         file:
            path: /etc/apt/keyrings/docker.gpg
            mode: 444
       - name: add docker repo
         shell: 'echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
   tee /etc/apt/sources.list.d/docker.list > /dev/null'





             

